Problema 3 [30 puntos]. La amitriptina es recetada por algunos médicos como un antidepresivo. Existen algunos efectos secundarios de esta droga como: pulsaciones cardiacas irregulares, presión arterial anormal, entre otras. Un conjunto de datos de 17 pacientes a los cuales se les administró esta droga fue recolectado en un estudio. Las variables respuestas fueron las siguientes:

* $Y_{1}=$ Nivel de plasma Total 
* $Y_{2}=$ Cantidad de amitriptina presente en el plasma Se midieron cinco variables prediuctoras 
* $Z_{1}=$ Género $(1$ Female, 0 Male) (GEN) 
* $Z_{2}=$ Cantidad de antidepresivo ingerido (AMT) 
* $Z_{3}=$ Medición de la onda cardiaca (PR) 
* $Z_{4}=$ Presión diastólica (DIAP) 
* $Z_{5}=$ Medida de onda cardiaca (QRS)

a) Escriba un modelo de regresión con respuesta multivariada para abordar este problema.

In [1]:
#importamos las librerias 

import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
#ingresamos los datos

y_1 = np.array([3389, 1101, 1131, 596, 896, 1767, 807, 1111, 645, 628, 1360, 652, 860, 500, 781, 1070, 1754])
y_2 = np.array([3149, 653, 810, 448, 844, 1450, 493, 941, 547, 392, 1283, 458, 722, 384, 501, 405, 1520])

z_1 = np.array([1 ,1 ,0 ,1 ,1 ,1 ,1 ,0 ,1 ,1 ,1 ,1 ,1 ,0 ,0 ,0 ,1])
z_2 = np.array([7500, 1975, 3600, 675, 750, 2500, 350, 1500, 375, 1050, 3000, 450, 1750, 2000, 4500, 1500, 3000])
z_3 = np.array([220, 200, 205, 160, 185, 180, 154, 200, 137, 167, 180, 160, 135, 160, 180, 170, 180])
z_4 = np.array([0,  0,  60,  60,  70,  60,  80,  70,  60,  60,  60,  64,  90,  60,  0,  90,  0])
z_5 = np.array([140,  100,  111,  120,  83,  80,  98,  93,  105,  74,  80,  60,  79,  80,  100,  120,  129])

In [3]:
#los arreglamos para usar sklearn

X = np.array([z_1,z_2,z_3,z_4,z_5]).T

y = np.array([y_1, y_2]).T

In [4]:
X.shape

(17, 5)

In [5]:
y.shape

(17, 2)

In [6]:
#realizamos la regresión

reg = LinearRegression().fit(X, y)

In [7]:
#coef R^2

reg.score(X, y)

0.881745154243515

In [8]:
# coeficientes de la regresión

reg.coef_

array([[6.75650781e+02, 2.84851063e-01, 1.02721328e+01, 7.25117136e+00,
        7.59823965e+00],
       [7.63029762e+02, 3.06373400e-01, 8.89619768e+00, 7.20555972e+00,
        4.98705075e+00]])

In [9]:
# intercepto de la regresión

reg.intercept_

array([-2879.47824607, -2728.70854444])

b) Determine los estimadores de mínimos cuadrados, valores ajustados y residuos usando los valores de la tabla con las observaciones.

In [10]:
# generamos la matriz Z necesaria

z_0 = np.ones(17)
Z = np.array([z_0,z_1,z_2,z_3,z_4,z_5]).T

In [11]:
Z.shape

(17, 5)

Usando 
$$
\begin{aligned}
\widehat{\boldsymbol{\beta}} &=\left(\boldsymbol{Z}^{\top} \boldsymbol{Z}\right)^{-1} \boldsymbol{Z}^{\top} \boldsymbol{Y} \\
\widehat{\boldsymbol{\Sigma}} &=\frac{1}{n}(\boldsymbol{Y}-\boldsymbol{Z} \widehat{\boldsymbol{\beta}})^{\top}(\boldsymbol{Y}-\boldsymbol{Z} \widehat{\boldsymbol{\beta}})
\end{aligned}
$$

Tenemos:

In [12]:
b = np.linalg.inv(Z.T.dot(Z)).dot(Z.T).dot(y)
b

array([[ 4.55316678e+02,  5.54232370e+02],
       [ 3.25402470e-01,  3.44801533e-01],
       [-1.12386315e+00, -1.90310308e+00],
       [ 1.38567934e+00,  1.64718531e+00],
       [ 2.49205328e+00,  1.48224691e-01]])

In [13]:
sigma = 1/17*(y-Z.dot(b)).T.dot((y-Z.dot(b)))
sigma

array([[99522.15349997, 90853.62870014],
       [90853.62870014, 98750.83764068]])

In [14]:
e = y-Z.dot(b)
e

array([[ 391.52722917,  406.68735413],
       [ -21.41925474, -216.41724994],
       [-169.81562146, -156.43344645],
       [-281.33239519, -151.09499286],
       [ 100.70817617,  255.63492964],
       [ 417.96749076,  265.63325864],
       [  55.79181412,  -35.13587618],
       [ 518.91041589,  675.33044879],
       [-123.17970736,    9.79746652],
       [-248.85682869, -316.2555104 ],
       [-151.73374435,  -73.76750787],
       [  -8.13636006,  -61.20990774],
       [-334.6328251 , -338.67256498],
       [-253.49185917, -111.79566691],
       [-730.22107707, -722.87081288],
       [ 349.19549618,   45.29158342],
       [ 203.29640526,  254.80060104]])

c) Realice un análisis de residuos.

¿Son normales los residuos?

In [15]:
#usamos el codigo anterior

def Mahananobis(x, mu, sigma):
    '''Distancia de Mahananobis asumiento distribución normal multivariada N(mu, sigma)'''
    z = x-mu
    return float(z.dot(np.linalg.inv(sigma)).dot(z.T))

from scipy.stats import chi2

def chisplot(data):
    ''' Similar al chisplot de R'''
    X_bar = data.mean()
    
    S = np.zeros((data.shape[1],data.shape[1]))
    for i in data.index:
            S = S + np.array([data.loc[i]-X_bar]).T.dot(np.array([data.loc[i]-X_bar]))
    S = 1/(data.shape[0]-1)*S
    
    d_2 = [Mahananobis(data.loc[i], X_bar, S) for i in data.index]
    d_2.sort()
    j_star = [1/data.shape[0]*(i+1-1/2) for i in range(data.shape[0])]
    chi_sqrd = [chi2.ppf(i, data.shape[1]) for i in j_star]
    
    source = pd.DataFrame({'d_2':d_2,'chi_sqrd':chi_sqrd})
    return  alt.Chart(source).mark_circle(size=60).encode(
            x='d_2',
            y='chi_sqrd',
            )

In [16]:
import pandas as pd
import altair as alt

chisplot(pd.DataFrame(e))

alt.Chart(...)

Podemos concluir que los residuos son normales

d) Construya una región de confianza del $95 \%$ para ambas variables respuestas para $z_{1}=1, z_{2}=1200, z_{3}=140, z_{4}=70$ y $z_{5}=85$

In [18]:
from scipy.stats import f 

Z = np.array([z_1,z_2,z_3,z_4,z_5]).T
z_0 = np.array([1,1200,140,70,85]).T
m = 2
n = 17
r = 5
b_1 = b[:,0]
b_2 = b[:,1]

region = (m*(n-r-1)/(n-r-m)*f.isf(0.05, m,n-r-m))**0.5*(z_0.T.dot(np.linalg.inv(Z.T.dot(Z))).dot(z_0)*n/(n-r-1)*sigma[0,0])**0.5

for i in range(2):
    print('[',z_0.T.dot(b[:,i])-region, z_0.T.dot(b[:,i])+region,']')


[ 542.7484036435694 1451.8133636739292 ]
[ 374.9293682804384 1283.994328310798 ]
