**Problema 3 [30 puntos]**. La amitriptina es recetada por algunos médicos como un antidepresivo. Existen algunos efectos secundarios de esta droga como: pulsaciones cardiacas irregulares, presión arterial anormal, entre otras. Un conjunto de datos de 17 pacientes a los cuales se les administró esta droga fue recolectado en un estudio. Las variables respuestas fueron las siguientes:

* $Y_{1}=$ Nivel de plasma Total 
* $Y_{2}=$ Cantidad de amitriptina presente en el plasma Se midieron cinco variables prediuctoras 
* $Z_{1}=$ Género $(1$ Female, 0 Male) (GEN) 
* $Z_{2}=$ Cantidad de antidepresivo ingerido (AMT) 
* $Z_{3}=$ Medición de la onda cardiaca (PR) 
* $Z_{4}=$ Presión diastólica (DIAP) 
* $Z_{5}=$ Medida de onda cardiaca (QRS)

a) Escriba un modelo de regresión con respuesta multivariada para abordar este problema.

In [1]:
#importamos las librerias 

import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
#ingresamos los datos

y_1 = np.array([3389, 1101, 1131, 596, 896, 1767, 807, 1111, 645, 628, 1360, 652, 860, 500, 781, 1070, 1754])
y_2 = np.array([3149, 653, 810, 448, 844, 1450, 493, 941, 547, 392, 1283, 458, 722, 384, 501, 405, 1520])

z_1 = np.array([1 ,1 ,0 ,1 ,1 ,1 ,1 ,0 ,1 ,1 ,1 ,1 ,1 ,0 ,0 ,0 ,1])
z_2 = np.array([7500, 1975, 3600, 675, 750, 2500, 350, 1500, 375, 1050, 3000, 450, 1750, 2000, 4500, 1500, 3000])
z_3 = np.array([220, 200, 205, 160, 185, 180, 154, 200, 137, 167, 180, 160, 135, 160, 180, 170, 180])
z_4 = np.array([0,  0,  60,  60,  70,  60,  80,  70,  60,  60,  60,  64,  90,  60,  0,  90,  0])
z_5 = np.array([140,  100,  111,  120,  83,  80,  98,  93,  105,  74,  80,  60,  79,  80,  100,  120,  129])

In [3]:
#los arreglamos para usar sklearn

X = np.array([z_1,z_2,z_3,z_4,z_5]).T

y = np.array([y_1, y_2]).T

In [4]:
X.shape

(17, 5)

In [5]:
y.shape

(17, 2)

In [6]:
#realizamos la regresión

reg = LinearRegression().fit(X, y)

In [7]:
#coef R^2

reg.score(X, y)

0.881745154243515

In [8]:
# coeficientes de la regresión

reg.coef_

array([[6.75650781e+02, 2.84851063e-01, 1.02721328e+01, 7.25117136e+00,
        7.59823965e+00],
       [7.63029762e+02, 3.06373400e-01, 8.89619768e+00, 7.20555972e+00,
        4.98705075e+00]])

In [9]:
# intercepto de la regresión

reg.intercept_

array([-2879.47824607, -2728.70854444])

b) Determine los estimadores de mínimos cuadrados, valores ajustados y residuos usando los valores de la tabla con las observaciones.

In [10]:
# generamos la matriz Z necesaria

z_0 = np.ones(17)
Z = np.array([z_0,z_1,z_2,z_3,z_4,z_5]).T

In [11]:
Z

array([[1.000e+00, 1.000e+00, 7.500e+03, 2.200e+02, 0.000e+00, 1.400e+02],
       [1.000e+00, 1.000e+00, 1.975e+03, 2.000e+02, 0.000e+00, 1.000e+02],
       [1.000e+00, 0.000e+00, 3.600e+03, 2.050e+02, 6.000e+01, 1.110e+02],
       [1.000e+00, 1.000e+00, 6.750e+02, 1.600e+02, 6.000e+01, 1.200e+02],
       [1.000e+00, 1.000e+00, 7.500e+02, 1.850e+02, 7.000e+01, 8.300e+01],
       [1.000e+00, 1.000e+00, 2.500e+03, 1.800e+02, 6.000e+01, 8.000e+01],
       [1.000e+00, 1.000e+00, 3.500e+02, 1.540e+02, 8.000e+01, 9.800e+01],
       [1.000e+00, 0.000e+00, 1.500e+03, 2.000e+02, 7.000e+01, 9.300e+01],
       [1.000e+00, 1.000e+00, 3.750e+02, 1.370e+02, 6.000e+01, 1.050e+02],
       [1.000e+00, 1.000e+00, 1.050e+03, 1.670e+02, 6.000e+01, 7.400e+01],
       [1.000e+00, 1.000e+00, 3.000e+03, 1.800e+02, 6.000e+01, 8.000e+01],
       [1.000e+00, 1.000e+00, 4.500e+02, 1.600e+02, 6.400e+01, 6.000e+01],
       [1.000e+00, 1.000e+00, 1.750e+03, 1.350e+02, 9.000e+01, 7.900e+01],
       [1.000e+00, 0.000e

Usando 
$$
\begin{aligned}
\widehat{\boldsymbol{\beta}} &=\left(\boldsymbol{Z}^{\top} \boldsymbol{Z}\right)^{-1} \boldsymbol{Z}^{\top} \boldsymbol{Y} \\
\widehat{\boldsymbol{\Sigma}} &=\frac{1}{n}(\boldsymbol{Y}-\boldsymbol{Z} \widehat{\boldsymbol{\beta}})^{\top}(\boldsymbol{Y}-\boldsymbol{Z} \widehat{\boldsymbol{\beta}})
\end{aligned}
$$

Tenemos:

In [12]:
b = np.linalg.inv(Z.T.dot(Z)).dot(Z.T).dot(y)
b

array([[-2.87947825e+03, -2.72870854e+03],
       [ 6.75650781e+02,  7.63029762e+02],
       [ 2.84851063e-01,  3.06373400e-01],
       [ 1.02721328e+01,  8.89619768e+00],
       [ 7.25117136e+00,  7.20555972e+00],
       [ 7.59823965e+00,  4.98705075e+00]])

In [13]:
sigma = 1/17*(y-Z.dot(b)).T.dot((y-Z.dot(b)))
sigma

array([[51176.95944034, 45039.79270646],
       [45039.79270646, 55335.81761062]])

In [14]:
e = y-Z.dot(b)
e

array([[ 132.82172075,  161.52768596],
       [ -72.00391573, -264.3532942 ],
       [-399.24769362, -373.85243774],
       [-382.84729526, -247.29456499],
       [-152.39129236,   15.78776868],
       [ 366.78644485,  217.13205622],
       [   4.49994231,  -83.74210164],
       [ 294.55680213,  462.72400744],
       [ 101.84067355,  223.03576304],
       [-180.05234962, -251.05363913],
       [-182.63908644, -103.05464388],
       [ 164.13388748,  102.04025643],
       [ -74.26618155,  -91.93873884],
       [ 123.30541339,  245.27247159],
       [-230.15941146, -248.9924144 ],
       [ 211.54488956,  -85.15162689],
       [ 274.117452  ,  321.91345235]])

c) Realice un análisis de residuos.

¿Son normales los residuos?

In [15]:
#usamos el codigo anterior

def Mahananobis(x, mu, sigma):
    '''Distancia de Mahananobis asumiento distribución normal multivariada N(mu, sigma)'''
    z = x-mu
    return float(z.dot(np.linalg.inv(sigma)).dot(z.T))

from scipy.stats import chi2

def chisplot(data):
    ''' Similar al chisplot de R'''
    X_bar = data.mean()
    
    S = np.zeros((data.shape[1],data.shape[1]))
    for i in data.index:
            S = S + np.array([data.loc[i]-X_bar]).T.dot(np.array([data.loc[i]-X_bar]))
    S = 1/(data.shape[0]-1)*S
    
    d_2 = [Mahananobis(data.loc[i], X_bar, S) for i in data.index]
    d_2.sort()
    j_star = [1/data.shape[0]*(i+1-1/2) for i in range(data.shape[0])]
    chi_sqrd = [chi2.ppf(i, data.shape[1]) for i in j_star]
    
    source = pd.DataFrame({'d_2':d_2,'chi_sqrd':chi_sqrd})
    return  alt.Chart(source).mark_circle(size=60).encode(
            x='d_2',
            y='chi_sqrd',
            )

In [16]:
import pandas as pd
import altair as alt

chisplot(pd.DataFrame(e))

alt.Chart(...)

Podemos concluir que los residuos son normales

d) Construya una región de confianza del $95 \%$ para ambas variables respuestas para $z_{1}=1, z_{2}=1200, z_{3}=140, z_{4}=70$ y $z_{5}=85$

In [17]:
from scipy.stats import f 

Z = np.array([z_1,z_2,z_3,z_4,z_5]).T
b = np.linalg.inv(Z.T.dot(Z)).dot(Z.T)
z_0 = np.array([1,1200,140,70,85]).T

m = 2
n = 17
r = 5

region = (m*(n-r-1)/(n-r-m)*f.isf(0.05, m,n-r-m))**0.5*(z_0.T.dot(np.linalg.inv(Z.T.dot(Z))).dot(z_0)*n/(n-r-1)*sigma[0,0])**0.5

for i in range(2):
    print('[',z_0.T.dot(b[:,i])-region, z_0.T.dot(b[:,i])+region,']')


[ -325.87514364807504 326.0117891320461 ]
[ -326.0090170493541 325.87791573076703 ]
